"""empty message

Revision ID: 3ebf15723a8d
Revises: 49e50deedf7a
Create Date: 2022-04-25 06:16:50.216373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebf15723a8d'
down_revision = '49e50deedf7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('image_file', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
