"""empty message

Revision ID: 41fc1f137638
Revises: bcdc0b743116
Create Date: 2022-04-21 01:13:09.717804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fc1f137638'
down_revision = 'bcdc0b743116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('image_path', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_path')
    op.drop_column('customer', 'is_admin')
    # ### end Alembic commands ###
