"""empty message

Revision ID: b0f8ea5d7971
Revises: e408d588b5ae
Create Date: 2022-04-17 02:07:33.655345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0f8ea5d7971'
down_revision = 'e408d588b5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorie', sa.Column('categorie_name', sa.String(length=50), nullable=False))
    op.drop_column('categorie', 'pr_categorie_description')
    op.add_column('product', sa.Column('product_name', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('product_price', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('product_color', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('product_size', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('product_description', sa.String(length=200), nullable=True))
    op.drop_column('product', 'pr_name')
    op.drop_column('product', 'pr_size')
    op.drop_column('product', 'pr_color')
    op.drop_column('product', 'pr_price')
    op.drop_column('product', 'pr_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('pr_description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('pr_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('pr_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('pr_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('pr_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('product', 'product_description')
    op.drop_column('product', 'product_size')
    op.drop_column('product', 'product_color')
    op.drop_column('product', 'product_price')
    op.drop_column('product', 'product_name')
    op.add_column('categorie', sa.Column('pr_categorie_description', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('categorie', 'categorie_name')
    # ### end Alembic commands ###
