"""empty message

Revision ID: b631f5c8d56b
Revises: b0f8ea5d7971
Create Date: 2022-04-17 02:25:19.530729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b631f5c8d56b'
down_revision = 'b0f8ea5d7971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_customer_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('product_customer_id_fkey', 'product', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
