"""empty message

Revision ID: b9cb75c07460
Revises: a8ab21e626a8
Create Date: 2022-05-05 08:51:06.892622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cb75c07460'
down_revision = 'a8ab21e626a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'confirmed')
    # ### end Alembic commands ###
