"""empty message

Revision ID: bcdc0b743116
Revises: c4ab8ec4df94
Create Date: 2022-04-21 01:11:11.747388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdc0b743116'
down_revision = 'c4ab8ec4df94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_file')
    op.drop_column('customer', 'is_admin')
    # ### end Alembic commands ###
