"""empty message

Revision ID: c4ab8ec4df94
Revises: 7360c7066c80
Create Date: 2022-04-21 01:08:46.333016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ab8ec4df94'
down_revision = '7360c7066c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_file')
    op.drop_column('customer', 'is_admin')
    # ### end Alembic commands ###
