"""empty message

Revision ID: cb7b4a43aa7c
Revises: e36570efc644
Create Date: 2022-04-24 01:35:11.284987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7b4a43aa7c'
down_revision = 'e36570efc644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
