"""empty message

Revision ID: d35677f5026a
Revises: 71ba4b525d6e
Create Date: 2022-05-03 17:44:25.030658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35677f5026a'
down_revision = '71ba4b525d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts_products',
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cart', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'product_id')
    op.drop_table('carts_products')
    # ### end Alembic commands ###
